spring.application.name=notifier
server.port=8081

spring.config.import=optional:file:./credentials.env.properties

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=techchallengefase3@gmail.com
spring.mail.password=irne wrcv urwm tzdm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true