spring.application.name=MedSched
spring.graphql.graphiql.enabled=true
server.port=8080

spring.datasource.url=jdbc:h2:mem:medhubdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=medsched
spring.datasource.password=p4ssw0rd
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=update
spring.graphql.schema.introspection.enabled=true

